name: "[CI/CD] Default FRVR CI"

on:
  workflow_call:
    inputs:
      fst_image:
        required: true
        type: string
      automation_image:
        required: true
        type: string  
    secrets:
      CR_PAT:
        required: true
      GH_TOKEN:
        required: true
      GCS_SA_KEY:
        required: true
      GCS_PROJECT:
        required: true
      GCS_DEVOPS_BINARY_BUCKET_KEY:
        required: true
      GH_PACKAGE_REGISTRY_PAT:
        required: true

jobs:
  # --- Run GUI Automated tests on WEB ---
  run_web_gui_automated_tests:
    name: GUI automated tests on web
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: /app/tests
    env:
      TEST_URL: ${{ needs.deploy_web.outputs.deploy_url }}
      HEADLESS: true
      TESTS_PATH: ${{ github.workspace }}/game/tests
    container:
      image: ${{ inputs.automation_image }}:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/game
      
      - name: Install sudo
        run: |
          apt-get update && apt-get -y install sudo

      - name: Checkout private actions
        uses: actions/checkout@v2
        with:
          repository: frvraps/frvr-gh-workflows
          token: ${{ secrets.GH_TOKEN }}
          ref: tests/webgui
          path: ./actions

      - name: '[FRVR Action] Web GUI tests'
        uses: ./actions/.github/actions/runwebguitests
        with:
          game_name: ${{ needs.gather_game_data.outputs.game_name }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        env:
          TEST_URL: ${{ needs.deploy_web.outputs.deploy_url }}
          HEADLESS: true
          TESTS_PATH: ${{ github.workspace }}/game/tests
          
      - name: Debug
        uses: mxschmitt/action-tmate@v3
