name: "[CI/CD] Deploy IOS"

on:
  workflow_call:
    inputs:
      github_run_number:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      FB_AUTODEPLOY_CREDENTIALS:
        required: true

jobs:
  ## --- GET GAME METADATA ---
  gather_game_data:
    name: Gather game metadata
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout game repo
        uses: actions/checkout@v2

      - name: Checkout private actions
        uses: actions/checkout@v2                     
        with:
          repository: frvraps/frvr-gh-workflows
          token: ${{ secrets.GH_TOKEN }}
          path: ./actions

      - id: metadata
        name: Execute metadata action
        uses: ./actions/.github/actions/getmetadata
    outputs:
      game_name: ${{ steps.metadata.outputs.game_name }}
      deploy_msg: ${{ steps.metadata.outputs.deploy_msg }}  

  ## --- Deploy Facebook Instant binary ---
  deploy_facebook_instant:
    name: Build FB Instant
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [gather_game_data]
    steps:
      - name: Checkout game repo
        uses: actions/checkout@v2
        with:
          path: frvr/game-${{ needs.gather_game_data.outputs.game_name }}

      - name: Checkout private actions
        uses: actions/checkout@v2                     
        with:
          repository: frvraps/frvr-gh-workflows
          token: ${{ secrets.GH_TOKEN }}
          path: ./actions

      - name: '[FRVR Action] Deploy Facebook Instant'
        uses: ./actions/.github/actions/deployfbinstant
        with:
          game_name: ${{ needs.gather_game_data.outputs.game_name }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          github_run_number: ${{ github.event.inputs.github_run_number }}
          FB_AUTODEPLOY_CREDENTIALS : ${{ secrets.FB_AUTODEPLOY_CREDENTIALS }}
