name: "Create a game build"

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      game_name:
        required: true
        type: string
      build_config:
        required: true
        type: string
      webhook_url:
        required: true
        type: string
      portal_build_id:
        required: true
        type: string
    secrets:
      CR_PAT:
        required: true
      GH_TOKEN:
        required: true
      AUTOMATED_RELEASE_CREDENTIALS:
        required: true
      GCS_SA_KEY:
        required: true
      GCS_PROJECT:
        required: true
      GH_PACKAGE_REGISTRY_PAT:
        required: true
      GCS_DEVOPS_BINARY_BUCKET_KEY:
        required: true
      ADMIN_PORTAL_API_KEY:
        required: true

jobs:
  build:
    name: Build binary for selected channel
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ACTION: ./actions/.github/actions/portal_build_${{ inputs.channel }}
    steps:

      - name: Checkout private actions
        uses: actions/checkout@v3
        with:
          repository: frvraps/frvr-gh-workflows
          token: ${{ secrets.GH_TOKEN }}
          ref: tests/portal
          path: ./actions
      
      - name: Setup build action
        run: |
          cd ./actions/.github/actions
          echo "Creating dynamic build action from 'portal_build_${{ inputs.channel }}'"
          mv portal_build_${{ inputs.channel }} portal_dynamic_build_action

      - name: '[FRVR Action] Perform build'
        uses: ./actions/.github/actions/portal_dynamic_build_action
        with:
          game_name: ${{ inputs.game_name }}
          build_config: ${{ inputs.build_config }}
          webhook_url: ${{ inputs.webhook_url }}
          portal_build_id: ${{ inputs.portal_build_id }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_PACKAGE_REGISTRY_PAT: ${{ secrets.GH_PACKAGE_REGISTRY_PAT }}
          GCS_DEVOPS_BINARY_BUCKET_KEY: ${{ secrets.GCS_DEVOPS_BINARY_BUCKET_KEY }}
          GCS_SA_KEY: ${{ secrets.GCS_SA_KEY }}
          ADMIN_PORTAL_API_KEY: ${{ secrets.ADMIN_PORTAL_API_KEY }}
