name: "[Pipeline] Build and deploy Web"

on:
  workflow_call:
    inputs:
      fst_image:
        required: true
        type: string
      game_branch:
        required: true
        type: string
      frvr_tools_branch:
        required: true
        type: string
      frvr_internal_branch:
        required: true
        type: string
    secrets:
      CR_PAT:
        required: true
      GH_TOKEN:
        required: true
      GCS_PROJECT:
        required: true
      GCS_SA_KEY:
        required: true
      ASANA_WORKSPACE_ID:
        required: true
      ASANA_PROJECT_ID:
        required: true
      ASANA_PAT:
        required: true

jobs:
  ## --- GET GAME METADATA ---
  gather_game_data:
    name: Gather game metadata
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout game repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.game_branch }}

      - name: Checkout private actions
        uses: actions/checkout@v2
        with:
          repository: frvraps/frvr-gh-workflows
          token: ${{ secrets.GH_TOKEN }}
          ref: XS-375-tweak-web-build-and-deploy-workflows
          path: ./actions

      - id: metadata
        name: Execute metadata action
        uses: ./actions/.github/actions/getmetadata
    outputs:
      fst_version: ${{ steps.metadata.outputs.fst_version }}
      game_name: ${{ steps.metadata.outputs.game_name }}
      deploy_msg: ${{ steps.metadata.outputs.deploy_msg }}

  # ## --- BUILD TO WEB ---
  # build_web:
  #   name: Build web version
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   needs: [gather_game_data]
  #   container:
  #     image: ${{ inputs.fst_image }}:${{ needs.gather_game_data.outputs.fst_version }}
  #     credentials:
  #       username: ${{ github.repository_owner }}
  #       password: ${{ secrets.CR_PAT }}
  #   steps:
  #     - name: Checkout game repo
  #       uses: actions/checkout@v2

  #     - name: Checkout private actions
  #       uses: actions/checkout@v2
  #       with:
  #         repository: frvraps/frvr-gh-workflows
  #         token: ${{ secrets.GH_TOKEN }}
  #         ref: XS-375-tweak-web-build-and-deploy-workflows
  #         path: ./actions

  #     - id: buildweb
  #       name: '[FRVR Action] Build action for WEB'
  #       uses: ./actions/.github/actions/buildweb
  #       with:
  #         game_name: ${{ needs.gather_game_data.outputs.game_name }}
  #         game_branch: ${{ github.event.inputs.game_branch }}
  #         frvr_internal_branch: ${{ github.event.inputs.frvr_internal_branch }}
  #         deploy_msg: ${{ needs.gather_game_data.outputs.deploy_msg }}
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #         GCS_SA_KEY: ${{ secrets.GCS_SA_KEY }}
  #         GCS_PROJECT: ${{ secrets.GCS_PROJECT }}

  # ## --- DEPLOY TO WEB ---
  # deploy_web:
  #   name: Deploy web version
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   needs: [gather_game_data, build_web]
  #   container:
  #     image: ${{ inputs.fst_image }}:${{ needs.gather_game_data.outputs.fst_version }}
  #     credentials:
  #       username: ${{ github.repository_owner }}
  #       password: ${{ secrets.CR_PAT }}
  #   steps:
  #     - name: Checkout game repo
  #       uses: actions/checkout@v2

  #     - name: Checkout private actions
  #       uses: actions/checkout@v2
  #       with:
  #         repository: frvraps/frvr-gh-workflows
  #         token: ${{ secrets.GH_TOKEN }}
  #         ref: XS-375-tweak-web-build-and-deploy-workflows
  #         path: ./actions

  #     - id: deployweb
  #       name: '[FRVR Action] Deploy action for WEB'
  #       uses: ./actions/.github/actions/deployweb
  #       with:
  #         game_name: ${{ needs.gather_game_data.outputs.game_name }}
  #         game_branch: ${{ github.event.inputs.game_branch }}
  #         frvr_internal_branch: ${{ github.event.inputs.frvr_internal_branch }}
  #         deploy_msg: ${{ needs.gather_game_data.outputs.deploy_msg }}
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #         GCS_SA_KEY: ${{ secrets.GCS_SA_KEY }}
  #         GCS_PROJECT: ${{ secrets.GCS_PROJECT }}
  #   outputs:
  #     deploy_url: ${{ steps.deployweb.outputs.deploy_url }}

  ## --- Create the Asana task ---
  create_asana_task:
    name: Create Asana task
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [gather_game_data] #, build_web, deploy_web]
    steps:
      - name: Checkout game repo
        uses: actions/checkout@v3
        with:
          path: frvr/game-${{ needs.gather_game_data.outputs.game_name }}
          ref: ${{ github.event.inputs.game_branch }}

      - name: Checkout private actions
        uses: actions/checkout@v3
        with:
          repository: frvraps/frvr-gh-workflows
          token: ${{ secrets.GH_TOKEN }}
          ref: XS-375-tweak-web-build-and-deploy-workflows  # TODO: Replace this with main
          path: ./actions

      - name: '[FRVR Action] Create Asana task'
        uses: ./actions/.github/actions/createasanaticket
        with:
          game_name: ${{ needs.gather_game_data.outputs.game_name }}
          game_branch: ${{ needs.gather_game_data.outputs.game_branch }}
          deployed_filename: ${{ needs.build_facebook_instant.outputs.filename }}
          frvr_tools_branch: 'stub'
          ticket_message: 'stub'
          channel: 'web'
          ASANA_WORKSPACE_ID: ${{ secrets.ASANA_WORKSPACE_ID }}
          ASANA_PROJECT_ID: ${{ secrets.ASANA_PROJECT_ID }}
          ASANA_PAT: ${{ secrets.ASANA_PAT }}
