name: "[Pipeline] Build and deploy Facebook Instant"

on:
  workflow_call:
    inputs:
      fst_image:
        required: true
        type: string
      game_branch:
        required: true
        type: string
      frvr_tools_branch:
        required: true
        type: string
      asana_check:
        required: true
        type: string
    secrets:
      CR_PAT:
        required: true
      GH_TOKEN:
        required: true
      GCS_PROJECT:
        required: true
      AUTOMATED_RELEASE_CREDENTIALS:
        required: true
      GH_PACKAGE_REGISTRY_PAT:
        required: true
      GCS_DEVOPS_BINARY_BUCKET_KEY:
        required: true
      GCS_SA_KEY:
        required: true
      ASANA_PAT:
        required: true
      GCS_MASTERDOC_SERVICE_ACCOUNT_KEY:
        required: true

jobs:
  ## --- GET GAME METADATA ---
  gather_game_data:
    name: Gather game metadata
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout game repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.game_branch }}

      - name: Checkout private actions
        uses: actions/checkout@v3
        with:
          repository: frvraps/frvr-gh-workflows
          token: ${{ secrets.GH_TOKEN }}
          ref: main
          path: ./actions

      - name: '[FRVR Action] Execute metadata action'
        id: metadata
        uses: ./actions/.github/actions/getmetadata
    outputs:
      fst_version: ${{ steps.metadata.outputs.fst_version }}
      game_name: ${{ steps.metadata.outputs.game_name }}

  ## --- Build Facebook Instant ---
  build_facebook_instant:
    name: Build FB Instant
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [gather_game_data]
    container:
      image: ${{ inputs.fst_image }}:${{ needs.gather_game_data.outputs.fst_version }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    steps:
      - name: Checkout game repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.game_branch }}

      - name: Checkout private actions
        uses: actions/checkout@v3
        with:
          repository: frvraps/frvr-gh-workflows
          token: ${{ secrets.GH_TOKEN }}
          ref: XS-369-Pipeline-merges
          path: ./actions

      - id: buildfbinstant
        name: '[FRVR Action] Build Facebook Instant'
        uses: ./actions/.github/actions/buildfbinstant_container
        with:
          game_name: ${{ needs.gather_game_data.outputs.game_name }}
          game_branch: ${{ github.event.inputs.game_branch }}
          frvr_tools_branch: ${{ github.event.inputs.frvr_tools_branch }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_PACKAGE_REGISTRY_PAT: ${{ secrets.GH_PACKAGE_REGISTRY_PAT }}
          GCS_DEVOPS_BINARY_BUCKET_KEY: ${{ secrets.GCS_DEVOPS_BINARY_BUCKET_KEY }}
          GCS_SA_KEY: ${{ secrets.GCS_SA_KEY }}
    outputs:
      filename: ${{ steps.buildfbinstant.outputs.filename }}
      build_json: ${{ steps.buildfbinstant.outputs.build_json }}

  # ## --- Deploy Facebook Instant binary ---
  # deploy_facebook_instant:
  #   name: Deploy FB Instant
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs: [gather_game_data, build_facebook_instant]
  #   steps:
  #     - name: Checkout game repo
  #       uses: actions/checkout@v3
  #       with:
  #         path: frvr/game-${{ needs.gather_game_data.outputs.game_name }}
  #         ref: ${{ github.event.inputs.game_branch }}

  #     - name: Checkout private actions
  #       uses: actions/checkout@v3
  #       with:
  #         repository: frvraps/frvr-gh-workflows
  #         token: ${{ secrets.GH_TOKEN }}
  #         ref: XS-369-Pipeline-merges
  #         path: ./actions

  #     - id: deploy_facebook
  #       name: '[FRVR Action] Deploy Facebook Instant'
  #       uses: ./actions/.github/actions/deployfbinstant
  #       with:
  #         game_name: ${{ needs.gather_game_data.outputs.game_name }}
  #         game_branch: ${{ github.event.inputs.game_branch }}
  #         frvr_tools_branch: ${{ github.event.inputs.frvr_tools_branch }}
  #         build_identifier: ${{ needs.build_facebook_instant.outputs.filename }}
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #         AUTOMATED_RELEASE_CREDENTIALS : ${{ secrets.AUTOMATED_RELEASE_CREDENTIALS }}
  #         GH_PACKAGE_REGISTRY_PAT: ${{ secrets.GH_PACKAGE_REGISTRY_PAT }}
  #         GCS_DEVOPS_BINARY_BUCKET_KEY: ${{ secrets.GCS_DEVOPS_BINARY_BUCKET_KEY }}
  #         GCS_SA_KEY: ${{ secrets.GCS_SA_KEY }}
  #   outputs:
  #     deploy_url: ${{ steps.deploy_facebook.outputs.deploy_url }}

  # ## --- Create the Asana task ---
  # create_asana_task:
  #   name: Create Asana task
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs: [gather_game_data, build_facebook_instant, deploy_facebook_instant]
  #   steps:
  #     - name: Checkout game repo
  #       uses: actions/checkout@v3
  #       with:
  #         path: frvr/game-${{ needs.gather_game_data.outputs.game_name }}
  #         ref: ${{ github.event.inputs.game_branch }}

  #     - name: Checkout private actions
  #       uses: actions/checkout@v3
  #       with:
  #         repository: frvraps/frvr-gh-workflows
  #         token: ${{ secrets.GH_TOKEN }}
  #         ref: main
  #         path: ./actions

  #     - id: asanatask
  #       name: '[FRVR Action] Create Asana task'
  #       uses: ./actions/.github/actions/createasanaticket
  #       with:
  #         game_name: ${{ needs.gather_game_data.outputs.game_name }}
  #         game_branch: ${{ github.event.inputs.game_branch }}
  #         deployed_filename: ${{ needs.build_facebook_instant.outputs.filename }}
  #         frvr_tools_branch: ${{ github.event.inputs.frvr_tools_branch }}
  #         ticket_message: 'Play Link: ${{ needs.deploy_facebook_instant.outputs.deploy_url }}'
  #         channel: 'Facebook Instant'
  #         asana_check: ${{ github.event.inputs.asana_check }}
  #         ASANA_PAT: ${{ secrets.ASANA_PAT }}
  #   outputs:
  #     task_url: ${{ steps.asanatask.outputs.task_url }}

  # ## --- Update Masterdoc ---
  # update_master_doc:
  #   name: Update Masterdoc
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs: [gather_game_data, build_facebook_instant, deploy_facebook_instant]
  #   steps:
  #     - name: Checkout game repo
  #       uses: actions/checkout@v3
  #       with:
  #         path: frvr/game-${{ needs.gather_game_data.outputs.game_name }}
  #         ref: ${{ github.event.inputs.game_branch }}

  #     - name: Checkout private actions
  #       uses: actions/checkout@v3
  #       with:
  #         repository: frvraps/frvr-gh-workflows
  #         token: ${{ secrets.GH_TOKEN }}
  #         ref: main
  #         path: ./actions

  #     - name: '[FRVR Action] Update Masterdoc'
  #       uses: ./actions/.github/actions/updatemasterdoc
  #       with:
  #         game_name: ${{ needs.gather_game_data.outputs.game_name }}
  #         game_branch: ${{ github.event.inputs.game_branch }}
  #         frvr_tools_branch: ${{ github.event.inputs.frvr_tools_branch }}
  #         build_json_filename: ${{ needs.build_facebook_instant.outputs.build_json }}
  #         channel: 'instant'
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #         GCS_DEVOPS_BINARY_BUCKET_KEY: ${{ secrets.GCS_DEVOPS_BINARY_BUCKET_KEY }}
  #         GCS_MASTERDOC_SERVICE_ACCOUNT_KEY: ${{ secrets.GCS_MASTERDOC_SERVICE_ACCOUNT_KEY }}

  # ## --- Notify slack ---
  # notify_slack:
  #   name: Notify slack
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs: [gather_game_data, build_facebook_instant, deploy_facebook_instant, create_asana_task]
  #   steps:
  #     - name: Checkout game repo
  #       uses: actions/checkout@v3
  #       with:
  #         path: frvr/game-${{ needs.gather_game_data.outputs.game_name }}
  #         ref: ${{ github.event.inputs.game_branch }}

  #     - name: Checkout private actions
  #       uses: actions/checkout@v3
  #       with:
  #         repository: frvraps/frvr-gh-workflows
  #         token: ${{ secrets.GH_TOKEN }}
  #         ref: main
  #         path: ./actions

  #     - name: '[FRVR Action] Slack Notify from Pipeline'
  #       uses: ./actions/.github/actions/slacknotifypipeline
  #       with:
  #         game_name: ${{ needs.gather_game_data.outputs.game_name }}
  #         game_branch: ${{ github.event.inputs.game_branch }}
  #         frvr_tools_branch: ${{ github.event.inputs.frvr_tools_branch }}
  #         channel: 'instant'
  #         task_url: ${{ needs.create_asana_task.outputs.task_url }}
  #         deploy_url: ${{ needs.deploy_facebook_instant.outputs.deploy_url }}