name: "[Pipeline] Build and deploy Google Play"

on:
  workflow_call:
    inputs:
      game_branch:
        required: true
        type: string
      frvr_tools_branch:
        required: true
        type: string
      frvr_internal_branch:
        required: true
        type: string
      fst_image:
        required: true
        type: string
      automation_image:
        required: true
        type: string
      channel:
        required: true
        type: string
    secrets:
      CR_PAT:
        required: true
      GH_TOKEN:
        required: true
      GCS_PROJECT:
        required: true
      AUTOMATED_RELEASE_CREDENTIALS:
        required: true
      GH_PACKAGE_REGISTRY_PAT:
        required: true
      GCS_DEVOPS_BINARY_BUCKET_KEY:
        required: true
      GCS_SA_KEY:
        required: true
      ASANA_WORKSPACE_ID:
        required: true
      ASANA_PROJECT_ID:
        required: true
      ASANA_PAT:
        required: true
      GCS_MASTERDOC_SERVICE_ACCOUNT_KEY:
        required: true


jobs:
  ## --- GET GAME METADATA ---
  gather_game_data:
    name: Gather game metadata
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout game repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.game_branch }}

      - name: Checkout private actions
        uses: actions/checkout@v3
        with:
          repository: frvraps/frvr-gh-workflows
          token: ${{ secrets.GH_TOKEN }}
          ref: feature/CH-464-add-support-for-GH-Actions-release-build # TODO: Replace this with main
          path: ./actions

      - name: '[FRVR Action] Execute metadata action'
        id: metadata
        uses: ./actions/.github/actions/getmetadata
    outputs:
      game_name: ${{ steps.metadata.outputs.game_name }}

  build_google_play:
    name: Build Google Play
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [gather_game_data]
    steps:
      - name: Checkout game repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.game_branch }}

      - name: Checkout private actions
        uses: actions/checkout@v3
        with:
          repository: frvraps/frvr-gh-workflows
          token: ${{ secrets.GH_TOKEN }}
          ref: feature/CH-464-add-support-for-GH-Actions-release-build # TODO: Replace this with main
          path: ./actions

      - id: generategoogleplay
        name: '[FRVR Action] Build Google Play'
        uses: ./actions/.github/actions/generategoogleplay
        with:
          game_name: ${{ needs.gather_game_data.outputs.game_name }}
          game_branch: ${{ github.event.inputs.game_branch }}
          frvr_tools_branch: ${{ github.event.inputs.frvr_tools_branch }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_PACKAGE_REGISTRY_PAT: ${{ secrets.GH_PACKAGE_REGISTRY_PAT }}
          GCS_DEVOPS_BINARY_BUCKET_KEY: ${{ secrets.GCS_DEVOPS_BINARY_BUCKET_KEY }}
          GCS_SA_KEY: ${{ secrets.GCS_SA_KEY }}
    outputs:
      filename: ${{ steps.generategoogleplay.outputs.filename }}
      build_json: ${{ steps.generategoogleplay.outputs.build_json }}
